### PR TITLE
Ruby 2_3 support. Corrected order of tokens at Ruby20parser.y and Ruby23parser.y

### PR DESCRIPTION
**Pull request by piotrhoppe**
Now the lexer for all version of Ruby takes tokens and their ids from the *src/org/jrubyparser/parser/Tokens.java* file. As I understand the lexer outputs is pass to the parser. But the parser takes the tokens and their ids form own definition witch are located in the *src/org/jrubyparser/parser/Ruby23Parser.java* file. And here is the issue. For example in the *Tokens.java:162* file the `tSYMBOLS_BEG` has a definition:
`int tSYMBOLS_BEG = Ruby20Parser.tSYMBOLS_BEG;` it is equal: `int tSYMBOLS_BEG = 283;`
but in the *Ruby23Parser.java:270* we has a definition:
`public static final int tSYMBOLS_BEG = 385;`
As you can see these values are different and more in the *Ruby23Parser.java:268* file we has a definition:
`public static final int tSTRING = 383;` that mean for Ruby 2.3 parser something else as for the lexer.
For this reason we will many syntax errors from Ruby 2.3 parser. For example the below code for current Ruby 2.3 parser has a [syntax error](https://imgur.com/06lGdlg) despite being correct:
```
class DoubleSplat
  def initialize(**params)
    @params = params
  end
end

class TestDoubleSplat < DoubleSplat
  def initialize(extra_param:, **params)
    super
  end
end

item = TestDoubleSplat.new(extra_param: "extra_value", regular_param: 'regular_value')

puts "Hello World"
puts item.inspect
```
Reason for that is differently understood the value 283 for lexer (it is `tSYMBOLS_BEG`) and parser (it is `tSTRING`).

I made changes that align token ids between particular parsers. After that, the above code [dose not contain a syntax error](https://imgur.com/XsxJxnl) and is parsed correctly.

### CODE REVIEW

**Comment by enebo** [comment]
I believe this solution will work and your analysis is correct.  

I also believe all Ruby versions only add tokens/types over time.  So another solution to this would be to always add newer ones at the end.  That may involves moving more stuff around though.   tSTRING is in all versions but tANDDOT starts at Ruby 2.3 (don't remember if this was really the first or not).   so tSTRING must precede tANDDOT and any other newer tokens (and of course be in the same order).

tLOWEST is not used by the lexer at all so I think so long as it is below any type or tokens it is fine staying in that part of the parser file (with other precedence statements).

Does that sound reasonable?

**Comment by piotrhoppe** [comment]
Yes of course. Thanks for your advice they very helpful. I'll prepare an update with taking into account your comments.
You mention that *tSTRING is in all versions* but I can found it only in *Ruby23Parser.y*, dose that mean I should to add it into versions: 1.8, 1.9, 2.0?

**Comment by enebo** [comment]
@piotrhoppe now that you mention it what is tSTRING?  When I saw it i thought it was tSTRING_CONTENT.  I will take a quick look.

**Comment by enebo** [comment]
@piotrhoppe This was a mistake made when 2.3 support was created.  tSTRING never existed in JRuby proper or in MRI.  The production which uses it should not be tSTRING but string1 and string1 is (from MRI 2.3.9):

```text
string		: tCHAR
		| string1
		| string string1
		    {
		    /*%%%*/
			$$ = literal_concat($1, $2);
		    /*%
			$$ = dispatch2(string_concat, $1, $2);
		    %*/
		    }
		;

string1		: tSTRING_BEG string_contents tSTRING_END
		    {
			heredoc_dedent($2);
			heredoc_indent = 0;
		    /*%%%*/
			$$ = $2;
		    /*%
			$$ = dispatch1(string_literal, $2);
		    %*/
		    }
		;
```

So in Lexer we should return tCHAR regardless of 1.8 or 1.9+ and the method questionMark should return tCHAR (not tSTRING or tINTEGER).  Removing that will address any ordering issues with tSTRING itself.

My suggestion above is how newer version of the language should work.  I do not remember ever seeing a token appear and then disappear.  This was something which was added only for this project.

**Comment by enebo** [comment]
I am having a little doubt that 1.8 should return tCHAR.  It is not actually used in 1.8 grammar.  It could probably stay tINTEGER if it is 1.8.

**Comment by enebo** [comment]
@piotrhoppe I fixed spec runs but this is not hooked up to GHA (or apparently travis-ci when it was still working). 

```text
jruby -S rspec
```

will run specs.  a GHA action would be a good thng to add and perhaps even a spec for tCHAR since that was changed and I do not think we are testing ?x behavior in specs.  I am not sure if you are working towards a goal for another project or you just wanted to hack on this one but the help is appreciated!

**Comment by piotrhoppe** [comment]
`jruby -S rspec` not work for me, probably I should do some preparation. It work with latest jruby? Where is the rspec file?
My goal is:
- to prepare  [Ruby and Rails plugin](https://github.com/piotrhoppe/community-ruby) to work with latest version of NetBeans. As far as I know you are its author ;).
- if I can add to it support for newer version of Ruby (2.6 or better 3.x).

I'm using NetBeans and this plugin in my professional work with Ruby 2.6. It works good, but not correctly support the newer syntax of Ruby.

Going back to the jruby-parser I found another issue related with this pull request, specifically with this: `dir.chomp(?/)`. I already have a patch. Be prepare for new pull request ;).

**Comment by enebo** [comment]
@piotrhoppe you need the rspec gem installed.  Otherwise if you are running from within the IDE you need to make sure the current working directory is the project root.

I tested with what is JRuby 9.4.0.0 but I do not think there is anything in those tests which are version sensitive (no outdated or new features).

I was supporting that plugin for a number of years but I just had too much work.  I am glad to hear you want to make it work for newer Ruby support.

**Pull request merged**
