### PR TITLE
Update parser with jruby/jruby's main line parser

### PR DESCRIPTION
**Pull request by jsyeo**
Creating this as per @headius's comment in https://github.com/jruby/jruby/issues/4172#issuecomment-249628867.

I removed some of the visitors that were using the old `NodeVisitor` interface as I only wanted to use the parser, lexer and AST. If you want those back I can put it back in this PR.

### CODE REVIEW

**Comment by chrisseaton** [comment]
Thanks very much for this. I needed to figure out how `jruby-parser` does precise source location information, and with this updated I can now do a simple diff to figure that out.

**Comment by enebo** [comment]
@jsyeo It is great you submitted this but I can see a few problems as submitted:
1. package names changed
1. a bunch of methods which were only on jruby-parser were deleted in the merge
1. all version support for jruby-parser was removed
1. some class names are jruby proper names and not jruby-parser ones.

In some regards I am not against these changes (like perhaps supporting 1.8 grammar is not that important any more) but Netbeans Ruby support depends on all of these things and will require updating approximately 190,000 lines of code.  So I am more inclined to reject it as is.

@jsyeo for your needs would you be willing to use jruby-parser APIs and change your project to use these slightly different APIs?  If so I am willing to work on merging the 2.3 parser iinto this codebase.  I am excited you are working something which needs parser support since we need more people supporting this work.  So don't take this as a negative comment.  I really want to work with you to make sure jruby-parser is usable by you.

**Comment by enebo** [comment]
@jsyeo for the more generic visitor we can major rev jruby-parser and I will happily check netbeans for that.  I need to look more at your PR to figure out which other changes you would like to have.

**Comment by jsyeo** [comment]
> Netbeans Ruby support depends on all of these things and will require updating approximately 190,000 lines of code

Hmmm okay. I would need to take a look at how the api is being used to see how I can fix that. I would assume the code for Netbeans Ruby is here https://github.com/nbruby/nbruby?

**Comment by enebo** [comment]
@jsyeo another thing I should point out about this library which is quite a bit different (and I suspect may have some bugs to work out yet) is that it works with Character's directly via a Reader.  This means that it does not use ByteList.  It also means it only works with CharSets defined in the JVM.  Since the main motivation of this was for IDE support this choice made sense.  Most encodings people run into in practice are in fact also Charsets in Java so this I think is ok.  It is another difference from the PR I should mention in case that is important?

**Comment by jsyeo** [comment]
> This means that it does not use ByteList.

Can it be extended to use ByteList?

**Comment by enebo** [comment]
@jsyeo yeah I think there is two general ways:

  1. Make Lexer a little smarter.  In a handful of places we do byte logic and mbclen and stuff (largely stuff we need from the jcodings project -- which is not a dependency or bytelist for that matter)
  2. Make a ByteListReader extends Reader.  I would almost consider making this a companion .jar since it would depend on jcodings + bytelist.  It would not have to be though.

The second option feels a bit more appealing in that the lexer will be simpler but the first option can also work with only a handful of differences (which can be a condition of a subtype).

**Pull request closed without merging**
